listen:
  host: "0.0.0.0"
  port: 8080
  protocol: "http" # or tcp

load_balance:
  algorithms: "round_robin"  # or "least_connections", "weighted", etc.
  servers:
    - host: "127.0.0.1"
      port: 60001
      weight: 1
#      healthy: False
    - host: "127.0.0.1"
      port: 60002
      weight: 2
    - host: "127.0.0.1"
      port: 60003
      weight: 1

health_check:
  interval: 10    # seconds
  timeout: 2      # seconds
  path: "/health"
