listen:
  host: "0.0.0.0"
  port: 8080
  protocol: "http"

load_balance:
  algorithms: "round_robin"
  servers:
    - host: "192.168.1.10"
      port: 5000
      # weight: 1  # Missing 'weight'
    - host: "192.168.1.11"
      port: 5000
      weight: 2
    - host: "192.168.1.12"
      port: 5000
      weight: 1

health_check:
  interval: 10
  timeout: 2
  path: "/health"
  retries: 3
